Added Hooktheory's Theorytab
ciconia/awesome-music pull request #37
Opened 2021-03-02 02:50 UTC by wildwestrom

I use this database all the time. It helped me a lot with understanding roman numeral analysis and functional harmony.
It's not open source, but the database is totally free and users can freely contribute.

2021-03-06 23:13 UTC, wildwestrom commented
Perhaps the link itself could have a better description or be put into a different category
```markdown
* [Theorytab](https://www.hooktheory.com/theorytab) - a database of songs with their chord functions.
```

2021-03-12 09:21 UTC, ciconia requested changes
Please maintain the alphabetical ordering of links. Thanks!

2021-04-21 23:27 UTC, wildwestrom commented
It's in order now.

2021-04-24 20:50 UTC, ciconia approved these changes

2021-04-24 20:51 UTC, merged