Add leiter to readme
ciconia/awesome-music pull request #76
Opened 2024-12-08 10:28 UTC by kad1kad

2025-01-02 07:54 UTC, noteflakes requested changes
Please fix the ordering. Your entry should appear after "Leipzig".

2025-01-02 12:21 UTC, kad1kad commented
> Please fix the ordering. Your entry should appear after "Leipzig".

Done! Thanks for checking :)

2025-02-03 08:28 UTC, noteflakes commented
Closing for lack of response.

2025-02-03 08:29 UTC, merged

2025-02-03 08:29 UTC, noteflakes commented
Thanks for your contribution!